version: '3.8'

services:
  database:
    container_name: database
    image: postgres:13.6-alpine3.15
    environment:
      POSTGRES_DB: manga
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - data-db:/var/lib/postgresql/data:rw

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/app
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  data-db: